version: '3.8'

services:
  db:
    image: postgres
    container_name: url_shortener_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: url_shortener_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "host=db user=myuser password=mypassword dbname=shortener port=5432 sslmode=disable"
    ports:
      - "8080:8080"
