version: '3.8'

services:
  db:
    image: postgres
    container_name: url_shortener_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d shortener"]
      interval: 5s
      retries: 5
